name: spring_app

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - 9876:5432
    environment:
      POSTGRES_PASSWORD: docker_password
      POSTGRES_USER: docker_user
      POSTGRES_DB: docker_db
    networks:
      - spring_app

networks:
  spring_app:
    driver: bridge